# One-country pipeline walkthrough

Runs `backend/utils/pipeline._process_country` one step at a time, so every
intermediate is visible: the macro panel, the LLM payload, the raw article pool,
the stage-1 digests, the model's subscores and per-article impacts, and the
Top-3 that reach the dashboard.

**Pick a country by editing `ISO2` in the cell under _Pick a country_, then Run All.**

Before the first run, install a kernel into the project venv (it is deliberately
not in `requirements.txt`, which is runtime-only):

```
.venv\Scripts\python.exe -m pip install ipykernel
```

Two things to know:

- **This writes no snapshot.** The last step builds the payload
  `data_push.upsert_snapshot` would take and prints it, but does not call it.
  The one thing that does touch Postgres is the stage-1 digest cache in Step 2b
  (`article_digest`), which is scratch data keyed by article URL — nothing the
  dashboard reads.
- **It makes real network calls**, and **Steps 2b and 3 spend OpenAI credits**
  (one cheap digest call per article, then one scoring call). A country with no
  local macro panel also hits the World Bank once per indicator in Step 0, which
  is slow.

## Setup

Resolves the repo root, loads `backend/.env`, and routes the pipeline's logging
into the notebook. `force=True` on `basicConfig` is not optional — Jupyter
installs its own root handler, so a plain `basicConfig()` is silently a no-op
and no pipeline logs appear.

In [ ]:
import json
import logging
import os
import pathlib
import sys

import pandas as pd
from dotenv import load_dotenv

# Repo root = the folder holding backend/main.py, so this works whether the
# kernel's cwd is backend/ or the repo root.
PROJECT_ROOT = next(
    p for p in [pathlib.Path.cwd(), *pathlib.Path.cwd().parents]
    if (p / "backend" / "main.py").exists()
)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Same two-line load as main.py; every module reads os.getenv at call time.
load_dotenv(PROJECT_ROOT / "backend" / ".env")
load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-7s %(name)s: %(message)s",
    stream=sys.stdout,
    force=True,
)

pd.set_option("display.max_colwidth", 80)
pd.set_option("display.width", 200)

print(f"project root: {PROJECT_ROOT}")
for key in ("OPENAI_API_KEY", "CRAWLBASE_TOKEN", "CRAWLBASE_JS_TOKEN"):
    print(f"  {key:<20} {'set' if os.getenv(key) else 'MISSING'}")
print(f"  {'DATABASE_URL':<20} "
      f"{'set - used by the Step 2b digest cache only' if os.getenv('DATABASE_URL') else 'MISSING - Step 2b just skips its cache'}")

project root: D:\Coding\ai-country-risk
  OPENAI_API_KEY       set
  CRAWLBASE_TOKEN      set
  CRAWLBASE_JS_TOKEN   set
  DATABASE_URL         set - used by the Step 2b digest cache only

In [ ]:
from backend.utils import constants, data_retrieval
from backend.utils.ai import client as ai_client
from backend.utils.ai import digest_engine, langchain_llm
from backend.utils.data_fetching import country_data_fetch
from backend.utils.data_upsert import data_push
from backend.utils.news_fetching import article_enrichment, article_ranking

# Payload window and article cap, mirrored from backend/utils/pipeline.py:32-37.
SINCE_YEAR = 2015
LOOKBACK_YEARS = 10
DELTA_HORIZONS = (1, 5)
MAX_ARTICLES = 20

print(f"pipeline modules loaded - scoring model: {ai_client.MODEL_NAME}, "
      f"digest model: {ai_client.DIGEST_MODEL_NAME}")

pipeline modules loaded - scoring model: gpt-4o-2024-08-06, digest model: gpt-4o-mini-2024-07-18

## Pick a country

The table below is `constants.COUNTRY_ROSTER`. `has_panel` says whether the
macro panel is already on disk — those countries skip the slow World Bank
backfill in Step 0.

In [ ]:
roster = pd.DataFrame(constants.COUNTRY_ROSTER)
roster["has_panel"] = roster["iso2"].map(
    lambda c: country_data_fetch.has_country_partition(country_data_fetch.PANEL_DIR, c)
)

print(f"{len(roster)} countries, {int(roster.has_panel.sum())} with a local macro panel")
roster.sort_values(["has_panel", "tier", "name"], ascending=[False, True, True])

48 countries, 5 with a local macro panel

                    name iso2 iso3     tier      lat       lng  has_panel
14           New Zealand   NZ  NZL       DM -41.5000  173.0000       True
16              Portugal   PT  PRT       DM  39.7000   -8.0000       True
22         United States   US  USA       DM  39.7500 -100.5000       True
27               Czechia   CZ  CZE       EM  49.8200   15.4700       True
43                Taiwan   TW  TWN       EM  23.7000  120.9600       True
0              Australia   AU  AUS       DM -24.6809  134.5300      False
1                Austria   AT  AUT       DM  47.6082   14.3738      False
2                Belgium   BE  BEL       DM  50.6003    4.7000      False
3                 Canada   CA  CAN       DM  60.9215 -108.0070      False
4                Denmark   DK  DNK       DM  55.6761   10.5683      False
5                Finland   FI  FIN       DM  63.3000   25.6200      False
6                 France   FR  FRA       DM  46.6000    2.0000      False
7                Germany   DE  DEU       DM  51.2000   10.5000      False
8   Hong Kong SAR, China   HK  HKG       DM  22.3193  114.1694      False
9                Ireland   IE  IRL       DM  52.8000   -8.0000      False
10                Israel   IL  ISR       DM  31.0000   35.0000      False
11                 Italy   IT  ITA       DM  42.6000   12.8000      False
12                 Japan   JP  JPN       DM  36.5000  139.2000      False
13           Netherlands   NL  NLD       DM  52.2500    5.7000      False
15                Norway   NO  NOR       DM  61.2000    8.7000      False
17             Singapore   SG  SGP       DM   1.3521  103.8198      False
18                 Spain   ES  ESP       DM  39.4000   -4.8000      False
19                Sweden   SE  SWE       DM  59.6500   14.5000      False
20           Switzerland   CH  CHE       DM  46.7500    8.0000      False
21        United Kingdom   GB  GBR       DM  54.7500   -3.5000      False
23                Brazil   BR  BRA       EM -10.3000  -53.3000      False
24                 Chile   CL  CHL       EM -31.8000  -71.1000      False
25                 China   CN  CHN       EM  35.0000  105.0000      False
26              Colombia   CO  COL       EM   4.0000  -73.0000      False
28                 Egypt   EG  EGY       EM  26.2000   29.3000      False
29                Greece   GR  GRC       EM  39.0000   22.3000      False
30               Hungary   HU  HUN       EM  47.1500   19.5000      False
31                 India   IN  IND       EM  22.3500   78.5000      False
32             Indonesia   ID  IDN       EM  -2.5000  118.0000      False
33                Kuwait   KW  KWT       EM  29.3100   47.4800      False
34              Malaysia   MY  MYS       EM   4.5000  102.2000      False
35                Mexico   MX  MEX       EM  23.6000 -102.0000      False
36                  Peru   PE  PER       EM  -7.0000  -75.0000      False
37           Philippines   PH  PHL       EM  13.0000  122.5000      False
38                Poland   PL  POL       EM  52.2297   19.0000      False
39                 Qatar   QA  QAT       EM  25.2854   51.0310      False
40          Saudi Arabia   SA  SAU       EM  25.5600   42.3500      False
41          South Africa   ZA  ZAF       EM -28.9000   25.0000      False
42           South Korea   KR  KOR       EM  36.6000  127.8300      False
44              Thailand   TH  THA       EM  15.0000  101.0000      False
45                Turkey   TR  TUR       EM  39.3000   35.3000      False
46  United Arab Emirates   AE  ARE       EM  24.0000   54.0000      False
47                Russia   RU  RUS  Special  64.7000   97.7000      False

In [ ]:
ISO2 = "PT"   # <-- change country here

ENTRY = next(c for c in constants.COUNTRY_ROSTER if c["iso2"] == ISO2)
NAME, ISO3 = ENTRY["name"], ENTRY["iso3"]

print(f"{NAME}  ({ISO2}/{ISO3})  tier={ENTRY['tier']}  map=({ENTRY['lat']}, {ENTRY['lng']})")

Portugal  (PT/PRT)  tier=DM  map=(39.7, -8.0)

## Step 0 — macro panel

Each country's World Bank indicators live in a Parquet partition under
`backend/data/wb_panel_wide/country_code=XX/`. If this country has none, the
real backfill runs with the roster temporarily narrowed to this one entry — the
same trick `backend/tests/live_country_check.py` uses. Expect a few minutes and
one World Bank call per indicator.

The panel is then read back through DuckDB, exactly as the pipeline reads it.

In [ ]:
if country_data_fetch.has_country_partition(country_data_fetch.PANEL_DIR, ISO2):
    print(f"panel already on disk for {ISO2}")
else:
    print(f"no panel for {ISO2} - building it (slow: one World Bank call per indicator)")
    full_roster = constants.COUNTRY_ROSTER
    constants.COUNTRY_ROSTER = [ENTRY]
    try:
        country_data_fetch.backfill_missing_panels()
    finally:
        constants.COUNTRY_ROSTER = full_roster

panel = data_retrieval.query_macro_panel(ISO2)
print(f"panel: {panel.shape[0]} years x {panel.shape[1]} columns")
panel.tail(15)

panel already on disk for PT
panel: 26 years x 11 columns

    year  INFLATION  UNEMPLOYMENT  FDI_PCT_GDP  POL_STABILITY  RULE_OF_LAW  GINI_INDEX  GDP_PC_GROWTH  INT_PAYM_PCT_REV  POL_CORRUPTION country_code
11  2011   3.653011        12.715     4.236488       0.783900     0.867073        36.3      -1.568857         11.755316           0.091           PT
12  2012   2.773339        15.509     7.215352       0.841201     0.888092        36.0      -3.661115         12.959271           0.087           PT
13  2013   0.274417        16.237     6.436543       0.763400     0.900620        36.2      -0.439198         12.157183           0.091           PT
14  2014  -0.278153        13.880     5.438510       0.940371     1.018187        35.6       1.286046         12.409146           0.091           PT
15  2015   0.487939        12.405     0.635222       1.000434     1.127288        35.5       2.011396         11.739378           0.093           PT
16  2016   0.607397        11.058     3.562830       0.958808     1.115692        35.2       2.326431         10.823892           0.104           PT
17  2017   1.368614         8.878     5.020416       1.054818     1.172268        33.8       3.567001          9.951020           0.094           PT
18  2018   0.993716         6.966     3.465843       1.091740     1.130340        33.5       3.111237          8.748283           0.100           PT
19  2019   0.338178         6.422     4.503894       0.994125     1.116551        32.8       2.721302          7.744142           0.105           PT
20  2020  -0.012438         6.850     1.814146       0.983046     1.183053        34.7      -8.301071          7.420530           0.121           PT
21  2021   1.265657         6.712     3.608360       0.958440     1.169078        34.6       4.899131          6.005810           0.131           PT
22  2022   7.832691         6.138     5.083689       0.886941     1.125686        36.3       6.242470          4.953870           0.139           PT
23  2023   4.311282         6.498     3.963254       0.789030     1.082429        33.9       1.698034          5.509847           0.172           PT
24  2024   2.416132         6.500     4.299741       0.536927     1.072155         NaN       1.101075          5.406859           0.166           PT
25  2025   2.336016         6.164          NaN            NaN          NaN         NaN       0.825648               NaN           0.166           PT

## Step 1 — the LLM payload

`prepare_llm_payload_pretty` compresses that panel into what the prompt actually
sees: per indicator a latest value, 1-year and 5-year percent changes, and the
last 10 observations. `_meta.generated_at` is the timestamp that would become
the snapshot's `as_of`.

`ALL_INDICATORS` is the World Bank set plus the OWID Political Corruption Index,
merged in at ingest time.

In [ ]:
payload = data_retrieval.prepare_llm_payload_pretty(
    country_iso=ISO2,
    indicators=constants.ALL_INDICATORS,
    since=SINCE_YEAR,
    lookback=LOOKBACK_YEARS,
    deltas=DELTA_HORIZONS,
)

units = payload["_meta"]["units"]
indicators = pd.DataFrame([
    {
        "indicator": name,
        "unit": units.get(name, ""),
        "latest": v["latest"],
        "\u03941y": v["\u03941y"],
        "\u03945y": v["\u03945y"],
        "years": len(v["series"]),
    }
    for name, v in payload["indicators"].items()
]).set_index("indicator")

print(f"latest_year={payload['latest_year']}  generated_at={payload['_meta']['generated_at']}")
indicators

latest_year=2025  generated_at=2026-07-26T22:05Z

                                                                unit  latest    Δ1y    Δ5y  years
indicator
Inflation (% y/y)                                              % y/y    2.34 -0.080  2.348     10
Unemployment (% labour force)                                      %    6.16 -0.336 -0.686     10
FDI inflow (% GDP)                                             % GDP    4.30  0.336 -0.204     10
Political stability (z-score)                                z-score    0.54 -0.252 -0.457     10
Rule of law (z-score)                                        z-score    1.07 -0.010 -0.044     10
Income inequality (Gini)                                       index   33.90 -2.400  0.400      9
GDP per-capita growth (% y/y)                                  % y/y    0.83 -0.275  9.127     10
Interest payments (% revenue)                              % revenue    5.41 -0.103 -2.337     10
Political corruption index (0–1, higher = more corrupt)  index (0–1)    0.17  0.000  0.045     10

## Step 2 — news

Four Google News queries per country (broad, government, economic, security),
de-duplicated by URL and scored by the keyword heuristic in
`article_ranking.score_relevance`. Anything under 0.3 is dropped as noise —
unless that leaves fewer than 3 articles, in which case the bar is relaxed
rather than returning an empty pane.

In [ ]:
items = article_enrichment.fetch_relevant_news(NAME, max_articles=MAX_ARTICLES)

print(f"{len(items)} articles after de-dupe, scoring, and the relevance cut")
pd.DataFrame([
    {
        "relevance": it.get("relevance_score"),
        "published": it.get("published"),
        "source": it.get("source"),
        "title": it.get("title"),
    }
    for it in items
])

2026-07-26 18:05:49,164 INFO    backend.utils.news_fetching.source_filter: Loaded 1 blocked news source(s).

2026-07-26 18:05:52,651 INFO    httpx: HTTP Request: GET https://wwd.com/pop-culture/celebrity-news/meghan-markle-prince-harry-portugal-summer-1239081815/ "HTTP/1.1 200 OK"

2026-07-26 18:05:52,852 INFO    httpx: HTTP Request: GET https://www.yahoo.com/news/science/articles/possible-great-white-shark-glides-163349088.html "HTTP/1.1 200 OK"

2026-07-26 18:05:53,060 INFO    httpx: HTTP Request: GET https://www.goodnewsnetwork.org/last-circus-elephant-in-portugal-welcomed-to-pangea-sanctuary/ "HTTP/1.1 200 OK"

2026-07-26 18:05:53,347 INFO    httpx: HTTP Request: GET https://www.nottinghamforest.co.uk/news/2026/july/26/forest-continue-pre-season-preparations-in-portugal "HTTP/1.1 200 OK"

2026-07-26 18:05:53,574 INFO    httpx: HTTP Request: GET https://www.atptour.com/en/news/estoril-2026-savour-the-spectacle "HTTP/1.1 200 OK"

2026-07-26 18:05:53,773 INFO    httpx: HTTP Request: GET https://www.townandcountrymag.com/society/tradition/a73249229/meghan-markle-family-vacation-photos-july-2026/ "HTTP/1.1 200 OK"

2026-07-26 18:05:53,916 INFO    httpx: HTTP Request: GET https://www.travelandleisure.com/best-places-to-live-in-portugal-11958998 "HTTP/1.1 403 Forbidden"

2026-07-26 18:05:54,066 INFO    httpx: HTTP Request: GET https://www.gbnews.com/news/world/british-banker-jailed-murdering-teenager-portugal-brawl "HTTP/1.1 200 OK"

2026-07-26 18:05:54,172 INFO    httpx: HTTP Request: GET https://www.theportugalnews.com/news/2026-07-26/mcdonalds-portugal-generated-an-impact-of-777-million-on-the-national-gdp-in-2025/1060317 "HTTP/1.1 200 OK"

2026-07-26 18:05:54,371 INFO    httpx: HTTP Request: GET https://www.elle.com/culture/celebrities/a73249848/meghan-markle-archie-lilibet-european-vacation-photos/ "HTTP/1.1 200 OK"

2026-07-26 18:05:54,829 INFO    httpx: HTTP Request: GET https://fieldlevelmedia.com/atp-tour/luca-van-assche-beats-alexander-blockx-in-portugal-for-first-title/ "HTTP/1.1 200 OK"

2026-07-26 18:05:54,913 INFO    httpx: HTTP Request: GET https://www.rfi.fr/en/international/20260726-trauma-and-taboos-how-portugal-takes-care-of-migrants-mental-health "HTTP/1.1 403 Forbidden"

2026-07-26 18:05:55,280 INFO    httpx: HTTP Request: GET https://www.specchemonline.com/news/catalyxx-chooses-portugal-first-site "HTTP/1.1 200 OK"

2026-07-26 18:05:55,465 INFO    httpx: HTTP Request: GET https://www.hawaiitribune-herald.com/2026/07/26/features/steves-tranquil-tomar-offers-a-break-from-portugals-tourist-tumult/ "HTTP/1.1 200 OK"

2026-07-26 18:05:55,934 INFO    httpx: HTTP Request: GET https://www.seattletimes.com/life/food-drink/americans-are-choosing-portugal-in-record-numbers-and-the-trips-they-are-booking-are-nowhere-near-lisbon-or-the-algarve/ "HTTP/1.1 200 OK"

2026-07-26 18:06:00,172 INFO    httpx: HTTP Request: GET https://www.euractiv.com/news/portugals-president-hints-costa-for-eu-council-chief-as-corruption-case-flounders/ "HTTP/1.1 403 Forbidden"

2026-07-26 18:06:00,645 INFO    httpx: HTTP Request: GET https://portugal.gov.pt/en/gc25/communication/news/portugal-and-greece-strengthen-strategic-partnership "HTTP/1.1 200 OK"

2026-07-26 18:06:01,369 INFO    httpx: HTTP Request: GET https://www.governo.it/en/articolo/president-meloni-s-press-statement-prime-minister-montenegro-portugal/32377 "HTTP/1.1 200 OK"

2026-07-26 18:06:01,623 INFO    httpx: HTTP Request: GET https://www.heraldnews.com/story/news/local/ojornal/2026/07/20/flad-president-durao-barroso-on-preserving-portuguese-american-history-strengthen-portugal-u-s-ties/90988506007/ "HTTP/1.1 200 OK"

2026-07-26 18:06:01,883 INFO    httpx: HTTP Request: GET https://breakingdefense.com/2026/07/portugal-to-purchase-three-frigates-from-italys-fincantieri-meloni/ "HTTP/1.1 200 OK"

2026-07-26 18:06:01,996 INFO    httpx: HTTP Request: GET https://portugal.gov.pt/en/gc25/communication/news/portugal-strengthens-cooperation-with-italy "HTTP/1.1 200 OK"

2026-07-26 18:06:02,102 INFO    httpx: HTTP Request: GET https://portugal.gov.pt/en/gc25/communication/news/prime-minister-congratulates-new-prime-minister-of-the-united-kingdom "HTTP/1.1 200 OK"

2026-07-26 18:06:02,216 INFO    httpx: HTTP Request: GET https://portugal.gov.pt/en/gc25/communication/news/prime-minister-turning-knowledge-into-development "HTTP/1.1 200 OK"

2026-07-26 18:06:02,310 INFO    httpx: HTTP Request: GET https://portugal.gov.pt/en/gc25/communication/news/prime-minister-reaffirms-commitment-to-cooperation-between-portugal-and-mozambique "HTTP/1.1 200 OK"

2026-07-26 18:06:02,540 INFO    httpx: HTTP Request: GET https://portugal.gov.pt/en/gc25/communication/news/state-of-the-nation-government-guarantees-stability-to-continue-transforming-portugal "HTTP/1.1 200 OK"

2026-07-26 18:06:02,823 INFO    httpx: HTTP Request: GET https://portugal.gov.pt/en/gc25/communication/news/prime-minister-hosts-cape-verdean-counterpart-and-reaffirms-the-close-ties-between-both-counties "HTTP/1.1 200 OK"

2026-07-26 18:06:03,106 INFO    httpx: HTTP Request: GET https://portugal.gov.pt/en/gc25/communication/news/luis-montenegro-the-government-is-delivering-on-its-commitment-to-always-do-more "HTTP/1.1 200 OK"

2026-07-26 18:06:03,216 INFO    httpx: HTTP Request: GET https://portugal.gov.pt/en/gc25/communication/news/prime-minister-reiterates-portugals-support-to-venezuela "HTTP/1.1 200 OK"

2026-07-26 18:06:03,403 INFO    httpx: HTTP Request: GET https://www.reutersconnect.com/item/portugals-pm-socrates-shakes-hands-with-former-minister-of-foreign-affairs-freitas-do-amaral-in-lisbon/dGFnOnJldXRlcnMuY29tLDIwMDY6bmV3c21sX0dNMURTWVRXUkFBQQ "HTTP/1.1 403 Forbidden"

2026-07-26 18:06:08,656 INFO    httpx: HTTP Request: GET https://macaubusiness.com/portugal-government-will-do-all-it-can-to-protect-sines-refinery-minister/ "HTTP/1.1 200 OK"

2026-07-26 18:06:13,408 INFO    httpx: HTTP Request: GET https://www.cnbc.com/2026/07/15/ecb-interest-rates-outlook-iran-war-hormuz.html "HTTP/1.1 200 OK"

2026-07-26 18:06:14,172 INFO    httpx: HTTP Request: GET https://www.pbs.org/newshour/economy/federal-reserve-chair-warsh-emphasizes-political-independence-signals-focus-on-inflation "HTTP/1.1 200 OK"

2026-07-26 18:06:14,814 INFO    httpx: HTTP Request: GET https://www.ecb.europa.eu/press/key/date/2026/html/ecb.sp260629~cb5a2e2168.en.html "HTTP/1.1 200 OK"

2026-07-26 18:06:15,060 INFO    httpx: HTTP Request: GET https://www.reuters.com/world/europe/warsh-hits-international-stage-with-peers-sharing-an-inflation-problem-2026-07-01/ "HTTP/1.1 401 HTTP Forbidden"

2026-07-26 18:06:15,193 INFO    httpx: HTTP Request: GET https://kfgo.com/2026/07/08/imf-says-hopes-to-engage-on-central-banks-changes-to-forward-guidance/ "HTTP/1.1 200 OK"

2026-07-26 18:06:15,484 INFO    httpx: HTTP Request: GET https://www.c-span.org/program/international-telecasts/federal-reserve-chair-warsh-speaks-at-european-central-bank-forum/681817 "HTTP/1.1 200 OK"

2026-07-26 18:06:15,745 INFO    httpx: HTTP Request: GET https://www.axios.com/2026/07/01/warsh-central-banks-ecb-policy "HTTP/1.1 200 OK"

2026-07-26 18:06:15,901 INFO    httpx: HTTP Request: GET https://www.barrons.com/articles/kevin-warsh-europe-federal-reserve-inflation-fb47cb0f "HTTP/1.1 401 HTTP Forbidden"

2026-07-26 18:06:15,976 INFO    httpx: HTTP Request: GET https://odi.org/en/insights/global-monetary-tightening-and-the-fragility-behind-it/ "HTTP/1.1 200 OK"

2026-07-26 18:06:16,813 INFO    httpx: HTTP Request: GET https://www.aa.com.tr/en/americas/fed-chair-says-us-central-bank-charting-new-course-repeats-no-forward-guidance/3983568 "HTTP/1.1 200 OK"

2026-07-26 18:06:17,473 INFO    httpx: HTTP Request: GET https://www.afr.com/world/north-america/warsh-says-inflation-risks-have-eased-vows-price-stability-20260702-p60buo "HTTP/1.1 200 OK"

2026-07-26 18:06:17,629 INFO    httpx: HTTP Request: GET https://wtvbam.com/2026/07/01/feds-warsh-says-some-task-force-staffing-to-be-revealed-next-week/ "HTTP/1.1 200 OK"

2026-07-26 18:06:17,815 INFO    httpx: HTTP Request: GET https://www.investopedia.com/fed-chair-warsh-says-inflation-risks-have-diminished-12010616 "HTTP/1.1 200 OK"

2026-07-26 18:06:18,000 INFO    httpx: HTTP Request: GET https://www.reuters.com/business/finance/ai-hopes-fears-dominate-global-central-bank-meet-2026-07-01/ "HTTP/1.1 401 HTTP Forbidden"

2026-07-26 18:06:18,074 INFO    httpx: HTTP Request: GET https://www.reuters.com/world/uk/rate-cuts-are-not-back-table-britain-bank-englands-bailey-says-2026-07-01/ "HTTP/1.1 401 HTTP Forbidden"

2026-07-26 18:06:25,376 INFO    httpx: HTTP Request: GET https://breakingdefense.com/2026/07/portugal-to-purchase-three-frigates-from-italys-fincantieri-meloni/ "HTTP/1.1 200 OK"

2026-07-26 18:06:25,431 INFO    httpx: HTTP Request: GET https://www.euractiv.com/news/eu-countries-kill-sanctions-on-russian-fish/ "HTTP/1.1 403 Forbidden"

2026-07-26 18:06:25,909 INFO    httpx: HTTP Request: GET https://thedefensepost.com/2026/07/24/portugal-heavy-lift-drone/ "HTTP/1.1 200 OK"

2026-07-26 18:06:26,141 INFO    httpx: HTTP Request: GET https://www.espn.com/soccer/story/_/id/49289909/cristiano-ronaldo-portugal-world-cup-career-ends-whimper-spain-subs-win-late "HTTP/1.1 200 OK"

2026-07-26 18:06:26,228 INFO    httpx: HTTP Request: GET https://www.arabnews.com/node/2652173/world "HTTP/1.1 403 Forbidden"

2026-07-26 18:06:26,479 INFO    httpx: HTTP Request: GET https://www.vozpopuli.com/indux/en/portugal-is-developing-a-graphene-based-stealth-material-that-could-hide-planes-and-drones-from-radar-as-defense-powers-watch/7576/ "HTTP/1.1 200 OK"

2026-07-26 18:06:26,617 INFO    httpx: HTTP Request: GET https://www.espn.com/soccer/story/_/id/49255237/portugal-snatch-victory-cristiano-ronaldo-continue "HTTP/1.1 200 OK"

2026-07-26 18:06:27,013 INFO    httpx: HTTP Request: GET https://www.dazn.com/en-US/news/soccer/fifa-world-cup-26-why-portugal-ronaldo-crashed-out-of-tournament-spain-analysis/17o9zhmn13tdl1xtsi67wi8e2g "HTTP/1.1 200 OK"

2026-07-26 18:06:27,095 INFO    httpx: HTTP Request: GET https://nypost.com/2026/06/29/sports/two-youtubers-arrested-after-allegedly-sneaking-past-security-at-colombia-portugal-world-cup-game-cops/ "HTTP/1.1 200 OK"

2026-07-26 18:06:27,196 INFO    httpx: HTTP Request: GET https://www.britannica.com/video/time-lapse-video-Porto-Portugal/-241820 "HTTP/1.1 403 Forbidden"

2026-07-26 18:06:27,848 INFO    httpx: HTTP Request: GET https://www.nytimes.com/athletic/7408471/2026/07/01/portugal-world-cup-ronaldo-good/ "HTTP/1.1 200 OK"

2026-07-26 18:06:28,071 INFO    httpx: HTTP Request: GET https://sports.yahoo.com/articles/rafael-le-o-giving-portugal-073240295.html "HTTP/1.1 200 OK"

2026-07-26 18:06:29,132 INFO    httpx: HTTP Request: GET https://www.japantimes.co.jp/sports/2026/07/07/soccer/world-cup/spain-portugal-world-cup/ "HTTP/1.1 200 OK"

2026-07-26 18:06:29,533 INFO    httpx: HTTP Request: GET https://www.reuters.com/sports/soccer/leao-replaces-felix-portugal-against-unchanged-croatia-2026-07-02/ "HTTP/1.1 401 HTTP Forbidden"

2026-07-26 18:06:30,609 INFO    httpx: HTTP Request: GET https://securitybrief.com.au/story/lampion-malware-campaign-targets-users-in-portugal "HTTP/1.1 200 OK"

20 articles after de-dupe, scoring, and the relevance cut

    relevance             published                      source                                                                            title
0        1.00  2026-07-20T07:00:00Z                  Governo.it  President Meloni’s press statement with Prime Minister Montenegro of Portuga...
1        1.00  2026-07-16T22:47:00Z  XXV Governo Constitucional  State of the Nation: Government guarantees stability to continue transformin...
2        1.00  2026-07-16T17:03:00Z  XXV Governo Constitucional  Luís Montenegro: The Government is delivering on its commitment to always do...
3        1.00  2026-07-16T07:00:00Z              Macau Business  Portugal: Government will do all it can to protect Sines refinery – minister...
4        1.00  2026-07-15T12:51:00Z  XXV Governo Constitucional  Prime Minister: Turning knowledge into development - XXV Governo Constitucional
5        1.00  2026-07-08T15:46:01Z         The Mighty 790 KFGO  IMF says hopes to engage on central banks’ changes to forward guidance - The...
6        1.00  2026-07-01T07:00:00Z                         PBS  Federal Reserve Chair Warsh emphasizes political independence, signals focus...
7        1.00  2026-07-01T07:00:00Z              Anadolu Ajansı  Fed chair says US central bank charting ‘new course,’ repeats no forward gui...
8        1.00  2026-07-01T07:00:00Z                Investopedia  Fed Chair Warsh Says Inflation Is Too High, But Risks Have Diminished Lately...
9        1.00  2026-06-29T07:00:00Z       European Central Bank               Back to basics in an uncertain environment - European Central Bank
10       0.98  2026-07-20T22:08:00Z  XXV Governo Constitucional  Prime Minister congratulates new Prime Minister of the United Kingdom - XXV ...
11       0.98  2026-07-17T16:04:00Z  XXV Governo Constitucional  Prime Minister reaffirms commitment to cooperation between Portugal and Moza...
12       0.98  2026-06-29T13:34:00Z  XXV Governo Constitucional  Prime Minister reiterates Portugal’s support to Venezuela - XXV Governo Cons...
13       0.95  2026-07-09T16:35:00Z  XXV Governo Constitucional  Prime Minister hosts Cape Verdean counterpart and reaffirms the close ties b...
14       0.95  2026-07-01T07:00:00Z                       Axios               Top central bankers align on rewriting the policy playbook - Axios
15       0.95  2026-07-20T16:12:00Z  XXV Governo Constitucional         Portugal strengthens cooperation with Italy - XXV Governo Constitucional
16       0.90  2026-07-24T15:35:00Z                   Vozpopuli  Portugal is developing a graphene-based stealth material that could hide pla...
17       0.90  2026-07-02T07:00:00Z                         AFR                Warsh says inflation risks have eased, vows price stability - AFR
18       0.83  2026-07-26T11:31:54Z           The Portugal News  McDonald’s Portugal generated an impact of €777 million on the national GDP ...
19       0.83  2026-07-20T21:54:00Z      Fall River Herald News  Durão Barroso outlines vision for FLAD, preserving Portuguese-American histo...

### Resolve and enrich

Google News links are redirect wrappers; these get unwrapped to real publisher
URLs, denylisted sources are dropped, and one GET per article recovers a
summary, body text, and thumbnail. Each survivor then gets the stable id
(`a1`, `a2`, …) the model refers back to.

In [ ]:
before_count = len(items)
items = article_enrichment.resolve_and_enrich(items, ISO2)

# Stable ids for the model to cite back (pipeline.py:128-129).
for i, it in enumerate(items, start=1):
    it["id"] = f"a{i}"

print(f"{len(items)}/{before_count} survived the source denylist")
pd.DataFrame([
    {
        "id": it["id"],
        "source": it.get("source"),
        "words": len((it.get("content") or it.get("text") or "").split()),
        "image": bool(it.get("image")),
        "title": it.get("title"),
    }
    for it in items
]).set_index("id")

20/20 survived the source denylist

                         source  words  image                                                                            title
id
a1                   Governo.it   1004   True  President Meloni’s press statement with Prime Minister Montenegro of Portuga...
a2   XXV Governo Constitucional    462   True  State of the Nation: Government guarantees stability to continue transformin...
a3   XXV Governo Constitucional    530   True  Luís Montenegro: The Government is delivering on its commitment to always do...
a4               Macau Business    498   True  Portugal: Government will do all it can to protect Sines refinery – minister...
a5   XXV Governo Constitucional    608   True  Prime Minister: Turning knowledge into development - XXV Governo Constitucional
a6          The Mighty 790 KFGO    481   True  IMF says hopes to engage on central banks’ changes to forward guidance - The...
a7                          PBS    773   True  Federal Reserve Chair Warsh emphasizes political independence, signals focus...
a8               Anadolu Ajansı    470   True  Fed chair says US central bank charting ‘new course,’ repeats no forward gui...
a9                 Investopedia   1087  False  Fed Chair Warsh Says Inflation Is Too High, But Risks Have Diminished Lately...
a10       European Central Bank   2848   True               Back to basics in an uncertain environment - European Central Bank
a11  XXV Governo Constitucional    162   True  Prime Minister congratulates new Prime Minister of the United Kingdom - XXV ...
a12  XXV Governo Constitucional    140   True  Prime Minister reaffirms commitment to cooperation between Portugal and Moza...
a13  XXV Governo Constitucional    313   True  Prime Minister reiterates Portugal’s support to Venezuela - XXV Governo Cons...
a14  XXV Governo Constitucional    190   True  Prime Minister hosts Cape Verdean counterpart and reaffirms the close ties b...
a15                       Axios    586  False               Top central bankers align on rewriting the policy playbook - Axios
a16  XXV Governo Constitucional    373   True         Portugal strengthens cooperation with Italy - XXV Governo Constitucional
a17                   Vozpopuli    814   True  Portugal is developing a graphene-based stealth material that could hide pla...
a18                         AFR    105   True                Warsh says inflation risks have eased, vows price stability - AFR
a19           The Portugal News    386   True  McDonald’s Portugal generated an impact of €777 million on the national GDP ...
a20      Fall River Herald News   1134   True  Durão Barroso outlines vision for FLAD, preserving Portuguese-American histo...

## Step 2b — stage-1 digests

The scorer never sees raw article bodies. A cheap model (`gpt-4o-mini`) reads
each article's **full text** and returns a strict-JSON factual extraction plus a
0-100 `stage1_severity`. Every digest reaches the scorer; only the three
highest-severity articles are pasted in full.

Digests are cached in Postgres by `(country, as_of, url)` plus a hash of the
digested text, so re-running this cell on the same day costs nothing. `as_of` is
read from the payload the same way `upsert_snapshot` reads it, so the cache key
matches the snapshot's.

Nothing here raises: a per-article failure leaves `digest=None` (that article
degrades to its title and summary in the prompt), and a cache read/write problem
just means "no cache".

In [ ]:
AS_OF = data_push.payload_as_of(payload)   # the date upsert_snapshot would key on
items = digest_engine.digest_articles(items, country_display=NAME, iso2=ISO2, as_of=AS_OF)
fulltext_ids = digest_engine.select_fulltext_ids(items)

print(f"as_of={AS_OF}   full text goes to the scorer for: {fulltext_ids}")
pd.DataFrame([
    {
        "id": it["id"],
        "severity": it.get("stage1_severity"),
        "full_text": it["id"] in fulltext_ids,
        "about_country": (it.get("digest") or {}).get("directly_about_country"),
        "what_happened": (it.get("digest") or {}).get("what_happened"),
    }
    for it in items
]).sort_values("severity", ascending=False).set_index("id")

2026-07-26 18:06:45,464 INFO    httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-07-26 18:06:45,825 INFO    httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-07-26 18:06:46,395 INFO    httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-07-26 18:06:46,531 INFO    httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-07-26 18:06:46,946 INFO    backend.utils.ai.digest_engine: [PT] digests: ok=4 cached=16 failed=0

as_of=2026-07-26   full text goes to the scorer for: ['a3', 'a17', 'a1']

     severity  full_text  about_country                                                                    what_happened
id
a3       40.0       True           True  Prime Minister Luís Montenegro highlighted the reforms implemented by the Go...
a17      40.0       True           True  A Portuguese startup, GTechPlasma, claims its new graphene-based material co...
a2       25.0      False           True  The Government of Portugal emphasized the importance of political stability ...
a1       25.0       True           True  President Meloni welcomed Prime Minister Montenegro of Portugal to Rome for ...
a4       25.0      False           True  The Portuguese Government is monitoring the merger of energy company Galp an...
a5       25.0      False           True  Prime Minister Luís Montenegro opened the 1st Science and Innovation Meeting...
a7       25.0      False          False  Federal Reserve Chair Kevin Warsh emphasized the central bank's independence...
a6       25.0      False          False  The International Monetary Fund plans to engage with central banks on change...
a12      25.0      False           True  Prime Minister Luís Montenegro hosted the President of Mozambique Daniel Cha...
a11      25.0      False           True  Prime Minister Luís Montenegro congratulated Andy Burnham on his appointment...
a13      25.0      False           True  The Prime Minister Luís Montenegro left a message of condolence and hope to ...
a9       25.0      False           True  Fed Chair Kevin Warsh stated that inflation is too high but noted that the o...
a16      25.0      False           True  Prime Minister Luís Montenegro visited Italy and signed an agreement for the...
a19      25.0      False           True  McDonald’s operations in Portugal contributed €777 million to the national G...
a15      25.0      False           True  Central bankers from top Western democracies expressed a desire to communica...
a14      25.0      False           True  Prime Minister Luís Montenegro hosted the Prime Minister of Cape Verde Franc...
a20      25.0      False           True  Durão Barroso outlined his vision for the Luso-American Development Foundati...
a8        0.0      False          False  Federal Reserve Chair Kevin Warsh announced that the US central bank will no...
a10       0.0      False           True  Christine Lagarde delivered a speech at the ECB Forum on Central Banking dis...
a18       0.0      False          False  Federal Reserve chairman Kevin Warsh stated that price risks have come down ...

### What the mini model actually did

Each stage-1 call is deliberately narrow: a few thousand characters of one
article go in, a few hundred characters of strict JSON come out. The mini model
is an **extraction engine**, not an analyst — it is told to use only the text in
front of it and to write `"not stated"` rather than fill a gap from outside
knowledge. It never sees the macro payload, the other articles, or the scoring
rubric, and it never produces a risk score.

The one judgement it makes is `stage1_severity`, and that number is used for
exactly one thing: choosing which three articles the scorer reads in full.

In [ ]:
digested = [it for it in items if it.get("digest")]
chars_in = sum(len(digest_engine.article_input_text(it)) for it in digested)
chars_out = sum(len(json.dumps(it["digest"], ensure_ascii=False)) for it in digested)

print(f"MINI MODEL  ({ai_client.DIGEST_MODEL_NAME})")
print(f"  {len(digested)} calls, one per article")
print(f"  read    {chars_in:>8,} chars of article text")
print(f"  wrote   {chars_out:>8,} chars of JSON   "
      f"({chars_out / max(chars_in, 1):.0%} of what it read)")

# The highest-severity article, end to end.
focus = max(digested, key=lambda it: it.get("stage1_severity") or 0.0)
sent = digest_engine.article_input_text(focus)
returned = json.dumps(focus["digest"], indent=2, ensure_ascii=False)

print(f"\n{'=' * 78}\nONE CALL IN FULL - article {focus['id']}: {focus.get('title', '')[:60]}\n{'=' * 78}")
print(f"\n--- IN: the article text it read ({len(sent):,} chars, first 800 shown) ---\n")
print(sent[:800] + ("..." if len(sent) > 800 else ""))
print(f"\n--- OUT: the entire digest it returned ({len(returned):,} chars) ---\n")
print(returned)

MINI MODEL  (gpt-4o-mini-2024-07-18)
  20 calls, one per article
  read      89,069 chars of article text
  wrote     11,039 chars of JSON   (12% of what it read)

==============================================================================
ONE CALL IN FULL - article a3: Luís Montenegro: The Government is delivering on its commitm
==============================================================================

--- IN: the article text it read (3,566 chars, first 800 shown) ---

Luís Montenegro: The Government is delivering on its commitment to always do more
During the State of the Nation debate, the Prime Minister said that Portugal is changing and highlighted the measures implemented by the Government
Prime Minister Luís Montenegro said that Portugal is changing as a result of the reforms implemented over the past two years. Opening the State of the Nation debate in Parliament, he said that the Government is delivering on the commitments it made to the Portuguese people.
Higher incomes, housing and opportunities for young people
Luís Montenegro highlighted the measures introduced to increase household incomes, including personal income tax cuts, the gradual reduction of corporate income tax, and higher wages.
He also pointed to the delivery of 20,000 homes unde...

--- OUT: the entire digest it returned (818 chars) ---

{
  "actors": "Prime Minister Luís Montenegro said that the Government is delivering on its commitments to the Portuguese people.",
  "numbers": "20,000 homes, 84,000 teachers, 5,000 healthcare professionals, VAT reduced to 6%, increase in Solidarity Benefit for the Elderly, full reimbursement of medicines for vulnerable pensioners, extraordinary pension supplement, Single Social Benefit.",
  "transmission": "measures to increase household incomes, support for young people, strengthening of the National Health Service, increase in social protection benefits, investment in infrastructure and digital transformation.",
  "what_happened": "Prime Minister Luís Montenegro highlighted the reforms implemented by the Government that are changing Portugal.",
  "stage1_severity": 40,
  "directly_about_country": true
}

## Step 3 — LLM scoring 💸

One structured-output call rating investor risk over the next 12 months, given
the macro payload, **every** article's digest, and the full text of the three
highest-severity ones.

It never raises. Without `OPENAI_API_KEY`, or on a network or parse failure, it
returns `score=None` and no article scores — the rest of the notebook still
runs, the tables are just empty. If Step 2b produced no digests at all, it logs
an ERROR and falls back to the old title-and-summary prompt rather than skipping
the country. A country caught by the sanctions gate in `legal_restrictions.yaml`
is forced to `1.0` after the model runs.

### What the scoring model actually receives

`country_llm_score` assembles three blocks into `AI_PROMPT`. This cell builds
them with the same internal helpers the function calls, so what prints here is
what gets sent:

- **EVIDENCE_JSON** — the macro payload from Step 1.
- **ARTICLE_DIGESTS_JSON** — every article, as `{id, source, published_at,
  title, digest, stage1_severity}`. No article bodies. An article whose digest
  failed appears in the old `summary` shape instead, which is how you spot a
  degraded one.
- **FULL_TEXT** — only the three articles Step 2b ranked highest, verbatim, each
  capped at `_MAX_FULLTEXT_CHARS` (12,000).

So the scorer sees *breadth* from the digests and *depth* on the few articles
that earned it. Unlike the mini model it does hold the rubric — bands, hard
rules, guardrails — and it is the only model that outputs a risk score.

In [ ]:
evidence_json = json.dumps(payload, ensure_ascii=False)
digests_json = langchain_llm._digests_to_json(items)          # the prompt's builders,
fulltext = langchain_llm._fulltext_block(items, fulltext_ids)  # not a re-implementation

print(f"SCORING MODEL  ({ai_client.MODEL_NAME})  -  1 call")
print(f"  EVIDENCE_JSON        {len(evidence_json):>8,} chars   macro payload")
print(f"  ARTICLE_DIGESTS_JSON {len(digests_json):>8,} chars   all {len(items)} articles, digests only")
print(f"  FULL_TEXT            {len(fulltext):>8,} chars   {len(fulltext_ids)} articles verbatim: {', '.join(fulltext_ids)}")

# For contrast: what every article's full text would have cost.
all_text = sum(len(digest_engine.article_input_text(it)) for it in items)
print(f"\n  (all {len(items)} bodies in full would be {all_text:,} chars - "
      f"the digests carry them in {len(digests_json):,})")

print(f"\n{'=' * 78}\nARTICLE_DIGESTS_JSON - one entry, {len(items)} of these\n{'=' * 78}\n")
print(json.dumps(json.loads(digests_json)[0], indent=2, ensure_ascii=False))
print(f"\n{'=' * 78}\nFULL_TEXT - first 700 chars\n{'=' * 78}\n")
print(fulltext[:700] + ("..." if len(fulltext) > 700 else ""))

print(f"\n{'=' * 78}\nDIVISION OF LABOR\n{'=' * 78}")
pd.DataFrame([
    {
        "stage": "1 · digest",
        "model": ai_client.DIGEST_MODEL_NAME,
        "calls": len(digested),
        "reads": "one article's full text, nothing else",
        "returns": "facts + stage1_severity 0-100",
        "decides": "which 3 articles stage 2 reads in full",
    },
    {
        "stage": "2 · score",
        "model": ai_client.MODEL_NAME,
        "calls": 1,
        "reads": "macro payload + all digests + 3 full texts",
        "returns": "score, subscores, per-article impact + topic_group",
        "decides": "the risk score, and the dashboard Top-3",
    },
]).set_index("stage")

SCORING MODEL  (gpt-4o-2024-08-06)  -  1 call
  EVIDENCE_JSON           2,759 chars   macro payload
  ARTICLE_DIGESTS_JSON   15,459 chars   all 20 articles, digests only
  FULL_TEXT              15,551 chars   3 articles verbatim: a3, a17, a1

  (all 20 bodies in full would be 89,069 chars - the digests carry them in 15,459)

==============================================================================
ARTICLE_DIGESTS_JSON - one entry, 20 of these
==============================================================================

{
  "id": "a1",
  "source": "Governo.it",
  "published_at": "2026-07-20",
  "title": "President Meloni’s press statement with Prime Minister Montenegro of Portugal - Governo.it",
  "digest": {
    "actors": "President Meloni and Prime Minister Montenegro discussed opportunities for cooperation between Italy and Portugal.",
    "numbers": "2025 trade relations reached almost EUR 10 billion; the visit occurred on 20 July 2026; the Mattei Plan for Africa involves 18 African nations.",
    "transmission": "bilateral cooperation agreement signed by Foreign Ministers Tajani and Rangel; discussions on EU agenda and migration management.",
    "what_happened": "President Meloni welcomed Prime Minister Montenegro of Portugal to Rome for discussions on strengthening bilateral cooperation.",
    "stage1_severity": 25,
    "directly_about_country": true
  },
  "stage1_severity": 25.0
}

==============================================================================
FULL_TEXT - first 700 chars
==============================================================================

--- id: a3 · Luís Montenegro: The Government is delivering on its commitment to always do more - XXV Governo Constitucional ---
Luís Montenegro: The Government is delivering on its commitment to always do more
During the State of the Nation debate, the Prime Minister said that Portugal is changing and highlighted the measures implemented by the Government
Prime Minister Luís Montenegro said that Portugal is changing as a result of the reforms implemented over the past two years. Opening the State of the Nation debate in Parliament, he said that the Government is delivering on the commitments it made to the Portuguese people.
Higher incomes, housing and opportunities for young people
Luís Mon...

==============================================================================
DIVISION OF LABOR
==============================================================================

                             model  calls                                       reads                                             returns                                  decides
stage
1 · digest  gpt-4o-mini-2024-07-18     20       one article's full text, nothing else                       facts + stage1_severity 0-100   which 3 articles stage 2 reads in full
2 · score        gpt-4o-2024-08-06      1  macro payload + all digests + 3 full texts  score, subscores, per-article impact + topic_group  the risk score, and the dashboard Top-3

In [ ]:
llm_output = langchain_llm.country_llm_score(
    country_display=NAME,
    payload=payload,
    articles=items,
    fulltext_ids=fulltext_ids,
)

print(f"score: {llm_output.get('score')}\n")
print(llm_output.get("bullet_summary"))

2026-07-26 18:06:52,264 INFO    httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

score: 0.35

Portugal's investor risk is low-moderate, driven by stable political conditions and ongoing government reforms. The country is enhancing its defense capabilities and international cooperation, notably with Italy. Economic indicators show moderate volatility, with inflation and unemployment rates stabilizing. Political stability is supported by government reforms in housing, education, and health. However, political corruption remains a concern, slightly impacting governance. Overall, Portugal's economic and political environment is conducive to investment, with no significant conflict or regulatory uncertainty expected in the near term.

In [ ]:
display(pd.Series(llm_output.get("subscores") or {}, dtype="float64").to_frame("subscore"))

pd.DataFrame(llm_output.get("news_article_scores") or [])

                          subscore
conflict_war                  0.10
political_stability           0.35
governance_corruption         0.30
macroeconomic_volatility      0.25
regulatory_uncertainty        0.20

     id  impact                    topic_group
0    a1    0.25     portugal_italy_cooperation
1    a2    0.25   portugal_political_stability
2    a3    0.40    portugal_government_reforms
3    a4    0.25         portugal_energy_sector
4    a5    0.25    portugal_science_innovation
5    a6    0.25         global_monetary_policy
6    a7    0.25         global_inflation_focus
7    a8    0.00         global_monetary_policy
8    a9    0.25         global_inflation_focus
9   a10    0.00            ecb_monetary_policy
10  a11    0.25          portugal_uk_relations
11  a12    0.25  portugal_mozambique_relations
12  a13    0.25     portugal_venezuela_support
13  a14    0.25  portugal_cape_verde_relations
14  a15    0.25         global_monetary_policy
15  a16    0.25     portugal_italy_cooperation
16  a17    0.40    portugal_defense_innovation
17  a18    0.00         global_inflation_focus
18  a19    0.25       portugal_economic_impact
19  a20    0.25          portugal_us_relations

## Step 4 — Top-3 selection

The model groups articles covering the same underlying event into a shared
`topic_group`. With 3 or more distinct topics, the best article of each of the
top 3 topics wins — so the dashboard shows three *stories* rather than three
write-ups of one. With fewer topics, the remainder is backfilled by impact.

The table shows every candidate, not just the winners, so you can see what lost.

In [ ]:
imp_map, topic_map = article_ranking.impact_topic_maps(llm_output)
items_by_id = {it.get("id"): it for it in items if isinstance(it, dict) and it.get("id")}
top_ids = article_ranking.select_top_ids(items_by_id, imp_map, topic_map, ISO2)

print(f"top 3: {top_ids}  (from {len(items_by_id)} candidates, "
      f"{len(set(topic_map.values()))} distinct topics)")
pd.DataFrame([
    {
        "id": aid,
        "selected": aid in top_ids,
        "impact": imp_map.get(aid),
        "topic_group": topic_map.get(aid),
        "published": it.get("published"),
        "title": it.get("title"),
    }
    for aid, it in items_by_id.items()
]).sort_values("impact", ascending=False).set_index("id")

2026-07-26 18:06:52,290 INFO    backend.utils.news_fetching.article_ranking: [PT] AI identified 15 topics (used 1/article).

top 3: ['a3', 'a17', 'a16']  (from 20 candidates, 15 distinct topics)

     selected  impact                    topic_group             published                                                                            title
id
a3       True    0.40    portugal_government_reforms  2026-07-16T17:03:00Z  Luís Montenegro: The Government is delivering on its commitment to always do...
a17      True    0.40    portugal_defense_innovation  2026-07-24T15:35:00Z  Portugal is developing a graphene-based stealth material that could hide pla...
a2      False    0.25   portugal_political_stability  2026-07-16T22:47:00Z  State of the Nation: Government guarantees stability to continue transformin...
a1      False    0.25     portugal_italy_cooperation  2026-07-20T07:00:00Z  President Meloni’s press statement with Prime Minister Montenegro of Portuga...
a4      False    0.25         portugal_energy_sector  2026-07-16T07:00:00Z  Portugal: Government will do all it can to protect Sines refinery – minister...
a5      False    0.25    portugal_science_innovation  2026-07-15T12:51:00Z  Prime Minister: Turning knowledge into development - XXV Governo Constitucional
a7      False    0.25         global_inflation_focus  2026-07-01T07:00:00Z  Federal Reserve Chair Warsh emphasizes political independence, signals focus...
a6      False    0.25         global_monetary_policy  2026-07-08T15:46:01Z  IMF says hopes to engage on central banks’ changes to forward guidance - The...
a12     False    0.25  portugal_mozambique_relations  2026-07-17T16:04:00Z  Prime Minister reaffirms commitment to cooperation between Portugal and Moza...
a11     False    0.25          portugal_uk_relations  2026-07-20T22:08:00Z  Prime Minister congratulates new Prime Minister of the United Kingdom - XXV ...
a13     False    0.25     portugal_venezuela_support  2026-06-29T13:34:00Z  Prime Minister reiterates Portugal’s support to Venezuela - XXV Governo Cons...
a9      False    0.25         global_inflation_focus  2026-07-01T07:00:00Z  Fed Chair Warsh Says Inflation Is Too High, But Risks Have Diminished Lately...
a16      True    0.25     portugal_italy_cooperation  2026-07-20T16:12:00Z         Portugal strengthens cooperation with Italy - XXV Governo Constitucional
a19     False    0.25       portugal_economic_impact  2026-07-26T11:31:54Z  McDonald’s Portugal generated an impact of €777 million on the national GDP ...
a15     False    0.25         global_monetary_policy  2026-07-01T07:00:00Z               Top central bankers align on rewriting the policy playbook - Axios
a14     False    0.25  portugal_cape_verde_relations  2026-07-09T16:35:00Z  Prime Minister hosts Cape Verdean counterpart and reaffirms the close ties b...
a20     False    0.25          portugal_us_relations  2026-07-20T21:54:00Z  Durão Barroso outlines vision for FLAD, preserving Portuguese-American histo...
a8      False    0.00         global_monetary_policy  2026-07-01T07:00:00Z  Fed chair says US central bank charting ‘new course,’ repeats no forward gui...
a10     False    0.00            ecb_monetary_policy  2026-06-29T07:00:00Z               Back to basics in an uncertain environment - European Central Bank
a18     False    0.00         global_inflation_focus  2026-07-02T07:00:00Z                Warsh says inflation risks have eased, vows price stability - AFR

## Step 5 — images for the Top-3

Chosen articles still missing a thumbnail get one more try through Crawlbase,
which renders JavaScript. It costs a credit per call, hence the Top-3-only
scope, and no-ops entirely without `CRAWLBASE_TOKEN`.

In [ ]:
before_images = {aid: items_by_id[aid].get("image") for aid in top_ids}
article_enrichment.enrich_top_images(top_ids, items_by_id)

pd.DataFrame([
    {"id": aid, "before": before_images[aid], "after": items_by_id[aid].get("image")}
    for aid in top_ids
]).set_index("id")

                                                                              before                                                                            after
id
a3   https://edge.sitecorecloud.io/centrodeges65c9-cegere0de-prod6279-8af9/media/...  https://edge.sitecorecloud.io/centrodeges65c9-cegere0de-prod6279-8af9/media/...
a17  https://www.vozpopuli.com/indux/en/wp-content/uploads/2026/07/portugal-graph...  https://www.vozpopuli.com/indux/en/wp-content/uploads/2026/07/portugal-graph...
a16  https://edge.sitecorecloud.io/centrodeges65c9-cegere0de-prod6279-8af9/media/...  https://edge.sitecorecloud.io/centrodeges65c9-cegere0de-prod6279-8af9/media/...

## Step 6 — the Top-3 rows

These are the rows that would be written to `risk_snapshot_article` and rendered
on the country page, followed by a rough preview of how they look there.

In [ ]:
top_articles = article_ranking.build_top_articles(top_ids, items_by_id, imp_map)
pd.DataFrame(top_articles).set_index("rank")

,id,url,title,source,published_at,impact,summary,image
rank,,,,,,,,
1,a3,https://portugal.gov.pt/en/gc25/communication/news/luis-montenegro-the-gover...,Luís Montenegro: The Government is delivering on its commitment to always do...,XXV Governo Constitucional,2026-07-16T17:03:00Z,0.40,Luís Montenegro: The Government is delivering on its commitment to always do...,https://edge.sitecorecloud.io/centrodeges65c9-cegere0de-prod6279-8af9/media/...
2,a17,https://www.vozpopuli.com/indux/en/portugal-is-developing-a-graphene-based-s...,Portugal is developing a graphene-based stealth material that could hide pla...,Vozpopuli,2026-07-24T15:35:00Z,0.40,A Portuguese startup says its new graphene-based material could sharply redu...,https://www.vozpopuli.com/indux/en/wp-content/uploads/2026/07/portugal-graph...
3,a16,https://portugal.gov.pt/en/gc25/communication/news/portugal-strengthens-coop...,Portugal strengthens cooperation with Italy - XXV Governo Constitucional,XXV Governo Constitucional,2026-07-20T16:12:00Z,0.25,"Portugal strengthens cooperation with Italy On an official visit to Italy, P...",https://edge.sitecorecloud.io/centrodeges65c9-cegere0de-prod6279-8af9/media/...

In [ ]:
from IPython.display import HTML

HTML("".join(
    '<div style="display:flex;gap:12px;margin:12px 0;align-items:flex-start">'
    + (f'<img src="{a["image"]}" style="width:160px;border-radius:6px">' if a["image"] else "")
    + f'<div><b>#{a["rank"]} &middot; impact {a["impact"]}</b><br>'
      f'<a href="{a["url"]}" target="_blank">{a["title"]}</a><br>'
      f'<small>{a["source"]} &middot; {a["published_at"]}</small><br>'
      f'<small>{(a["summary"] or "")[:240]}</small></div></div>'
    for a in top_articles
))

## Step 7 — the snapshot payload (not written)

The pipeline would hand this dict to `data_push.upsert_snapshot`, which writes
`country`, `indicator`, `yearly_value`, `risk_snapshot`, and
`risk_snapshot_article`.

**This notebook stops here on purpose** — no snapshot write, so a run can never
overwrite today's real snapshot for this country. (Step 2b's `article_digest`
rows are the one exception, and nothing reads those but Step 2b itself.) Use
`backend/tests/live_country_check.py` when you want the write plus verification
and cleanup.

In [ ]:
snapshot = {**payload, "llm_output": llm_output, "top_articles": top_articles}

# What upsert_snapshot validates before it would open a transaction.
print(f"country={snapshot['country']}  as_of<-{snapshot['_meta']['generated_at']}  "
      f"indicators={len(snapshot['indicators'])}  articles={len(snapshot['top_articles'])}")
print(json.dumps(snapshot, indent=2, default=str, ensure_ascii=False)[:3000])

country=PT  as_of<-2026-07-26T22:05Z  indicators=9  articles=3
{
  "country": "PT",
  "latest_year": 2025,
  "indicators": {
    "Inflation (% y/y)": {
      "latest": 2.34,
      "Δ1y": -0.08,
      "Δ5y": 2.348,
      "series": {
        "2016": 0.61,
        "2017": 1.37,
        "2018": 0.99,
        "2019": 0.34,
        "2020": -0.01,
        "2021": 1.27,
        "2022": 7.83,
        "2023": 4.31,
        "2024": 2.42,
        "2025": 2.34
      }
    },
    "Unemployment (% labour force)": {
      "latest": 6.16,
      "Δ1y": -0.336,
      "Δ5y": -0.686,
      "series": {
        "2016": 11.06,
        "2017": 8.88,
        "2018": 6.97,
        "2019": 6.42,
        "2020": 6.85,
        "2021": 6.71,
        "2022": 6.14,
        "2023": 6.5,
        "2024": 6.5,
        "2025": 6.16
      }
    },
    "FDI inflow (% GDP)": {
      "latest": 4.3,
      "Δ1y": 0.336,
      "Δ5y": -0.204,
      "series": {
        "2015": 0.64,
        "2016": 3.56,
        "2017": 5.02,
        "2018": 3.47,
        "2019": 4.5,
        "2020": 1.81,
        "2021": 3.61,
        "2022": 5.08,
        "2023": 3.96,
        "2024": 4.3
      }
    },
    "Political stability (z-score)": {
      "latest": 0.54,
      "Δ1y": -0.252,
      "Δ5y": -0.457,
      "series": {
        "2015": 1.0,
        "2016": 0.96,
        "2017": 1.05,
        "2018": 1.09,
        "2019": 0.99,
        "2020": 0.98,
        "2021": 0.96,
        "2022": 0.89,
        "2023": 0.79,
        "2024": 0.54
      }
    },
    "Rule of law (z-score)": {
      "latest": 1.07,
      "Δ1y": -0.01,
      "Δ5y": -0.044,
      "series": {
        "2015": 1.13,
        "2016": 1.12,
        "2017": 1.17,
        "2018": 1.13,
        "2019": 1.12,
        "2020": 1.18,
        "2021": 1.17,
        "2022": 1.13,
        "2023": 1.08,
        "2024": 1.07
      }
    },
    "Income inequality (Gini)": {
      "latest": 33.9,
      "Δ1y": -2.4,
      "Δ5y": 0.4,
      "series": {
        "2015": 35.5,
        "2016": 35.2,
        "2017": 33.8,
        "2018": 33.5,
        "2019": 32.8,
        "2020": 34.7,
        "2021": 34.6,
        "2022": 36.3,
        "2023": 33.9
      }
    },
    "GDP per-capita growth (% y/y)": {
      "latest": 0.83,
      "Δ1y": -0.275,
      "Δ5y": 9.127,
      "series": {
        "2016": 2.33,
        "2017": 3.57,
        "2018": 3.11,
        "2019": 2.72,
        "2020": -8.3,
        "2021": 4.9,
        "2022": 6.24,
        "2023": 1.7,
        "2024": 1.1,
        "2025": 0.83
      }
    },
    "Interest payments (% revenue)": {
      "latest": 5.41,
      "Δ1y": -0.103,
      "Δ5y": -2.337,
      "series": {
        "2015": 11.74,
        "2016": 10.82,
        "2017": 9.95,
        "2018": 8.75,
        "2019": 7.74,
        "2020": 7.42,
        "2021": 6.01,
        "2022": 4.95,
        "2023": 5.51,
        "2024": 5.41
      }
    },
    "Political corruption index (0–1, higher = more corrupt)": {
      "latest": 0.17,
      "Δ1y": 0.0,
      "Δ5y": 0.045,
      "series": {
        "2016": 0.1,

## Summary

Everything the run produced, on one screen — the "did this make sense?" cell.

In [ ]:
print(f"{NAME} ({ISO2})  -  risk score {llm_output.get('score')}\n")
print(pd.Series(llm_output.get("subscores") or {}, dtype="float64").to_string(), "\n")
print(llm_output.get("bullet_summary"), "\n")
for a in top_articles:
    print(f"  #{a['rank']}  impact {a['impact']}  {a['title']}")
    print(f"      {a['source']} - {a['published_at']}")
    print(f"      {a['url']}\n")

Portugal (PT)  -  risk score 0.35

conflict_war                0.10
political_stability         0.35
governance_corruption       0.30
macroeconomic_volatility    0.25
regulatory_uncertainty      0.20

Portugal's investor risk is low-moderate, driven by stable political conditions and ongoing government reforms. The country is enhancing its defense capabilities and international cooperation, notably with Italy. Economic indicators show moderate volatility, with inflation and unemployment rates stabilizing. Political stability is supported by government reforms in housing, education, and health. However, political corruption remains a concern, slightly impacting governance. Overall, Portugal's economic and political environment is conducive to investment, with no significant conflict or regulatory uncertainty expected in the near term.

  #1  impact 0.4  Luís Montenegro: The Government is delivering on its commitment to always do more - XXV Governo Constitucional
      XXV Governo Constitucional - 2026-07-16T17:03:00Z
      https://portugal.gov.pt/en/gc25/communication/news/luis-montenegro-the-government-is-delivering-on-its-commitment-to-always-do-more

  #2  impact 0.4  Portugal is developing a graphene-based stealth material that could hide planes and drones from radar as defense powers watch - Vozpopuli
      Vozpopuli - 2026-07-24T15:35:00Z
      https://www.vozpopuli.com/indux/en/portugal-is-developing-a-graphene-based-stealth-material-that-could-hide-planes-and-drones-from-radar-as-defense-powers-watch/7576/

  #3  impact 0.25  Portugal strengthens cooperation with Italy - XXV Governo Constitucional
      XXV Governo Constitucional - 2026-07-20T16:12:00Z
      https://portugal.gov.pt/en/gc25/communication/news/portugal-strengthens-cooperation-with-italy